"""Generate PDF documents from generated application materials."""

from datetime import date

from fpdf import FPDF


def _sanitize(text: str) -> str:
    """Strip characters that built-in PDF fonts cannot render."""
    return text.encode("latin-1", "ignore").decode("latin-1")


class _PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "Generated by MagangHub AI Assistant", new_x="LMARGIN", new_y="NEXT", align="R")

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def _add_section_title(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, _sanitize(title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(180, 180, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)


def _add_paragraphs(pdf: FPDF, text: str) -> None:
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(30, 30, 30)
    for line in text.split("\n"):
        line = _sanitize(line).strip()
        if not line:
            pdf.ln(2)
            continue
        if line.startswith(("-", "•", "*")):
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 6, f"    {line}")
        else:
            pdf.set_font("Helvetica", "B" if line.isupper() and len(line) < 70 else "", 11)
            pdf.multi_cell(0, 6, line)
        pdf.ln(1)


def generate_cv_pdf(name: str, tailored_cv: str, job_title: str = "", company: str = "") -> bytes:
    """Return tailored CV as PDF bytes."""
    pdf = _PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, _sanitize(name or "Curriculum Vitae"), new_x="LMARGIN", new_y="NEXT")

    if job_title or company:
        pdf.set_font("Helvetica", "I", 11)
        pdf.set_text_color(60, 60, 60)
        subtitle = f"Tailored for: {job_title}"
        if company:
            subtitle += f" at {company}"
        pdf.cell(0, 8, _sanitize(subtitle), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)
    _add_section_title(pdf, "Professional Profile")
    _add_paragraphs(pdf, tailored_cv)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 6, f"Generated on {date.today().isoformat()}", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def generate_cover_letter_pdf(name: str, cover_letter: str, job_title: str = "", company: str = "") -> bytes:
    """Return cover letter as PDF bytes."""
    pdf = _PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, _sanitize(name or "Cover Letter"), new_x="LMARGIN", new_y="NEXT")

    if job_title or company:
        pdf.set_font("Helvetica", "I", 11)
        pdf.set_text_color(60, 60, 60)
        subtitle = f"Re: {job_title}"
        if company:
            subtitle += f" at {company}"
        pdf.cell(0, 8, _sanitize(subtitle), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)
    _add_paragraphs(pdf, cover_letter)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 6, f"Generated on {date.today().isoformat()}", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
